### ISSUE TITLE
Close the pymilk live feed window (shmImshow.py)

### ISSUE THREAD

**Issue by kevinbarjot** [scexao-org/FIRST_Ixion_control-software#7]
I've found a way to close the live feed window of pymilk. You can use os.system("pkill shmImshow.py"). I let you put it by yourself, i don't to touch too much what is opened on the computer right now. Be careful: if you have several live feeds opened by shmImshow.py, and if you use this command, it may close all the live feed windows.

For me, i find it useful when i want to change the size of the image (when you change the binning, the crop etc...). I close the live feed, i change the sizes/settings, i re-initialize the shared memory (self.data = SHM('name', ...) and you can use the same name (ixioim) and it works even if you change its size) finally i do os.system("shmImshow.py ixionim &") and it opens your new live feed with the new size.

I thought it would be useful for you ;)

**Comment by sebviev** [comment]
Ah yes, super useful ;-) !! Merci, je vais l'ajouter tout de suite !

**Comment by DasVinch** [comment]
You can `pkill` only the viewer you want
`pkill -f "python <shmname>"`, assuming that's the actual command line you started it with.

**Comment by sebviev** [comment]
Nice, Thanks !!!

**Comment by sebviev** [comment]
This issue was solved in the pull request #6 .
Closing the issue.

**Comment by kevinbarjot** [comment]
Yeah even better, thanks Vincent!
